<?php

print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
print "\n";
print "<head>\n";
print "<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n";
print "<title>Untitled 1</title>\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "\n";
print "<meta charset=\"utf-8\" />\n";
print "<b id=\"docs-internal-guid-493fbd1b-6bbf-ceb6-ead1-13c9aed1b285\" style=\"font-weight:normal;\">\n";
print "<p dir=\"ltr\" style=\"line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align: center;\">\n";
print "<span style=\"font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "WELCOME TO THE BEATGRID CORPORATE HOMEPAGE</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align: center;\">\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Powered by</span><span style=\"font-size:10pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "<img height=\"20\" src=\"https://lh5.googleusercontent.com/jVyhq9qc7MwSvX2W_7_qEO6VWV2vQ1Ma_RlQyn_T02FAU9qpia15n-N76LIse7r-PKyZmrS2FnlZU5kXJ9qgo1e-hMuGRhCo1MnTMV7xFGFuHFMPvaHcgiDWmdelnYRng5FAdC32\" style=\"border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);\" width=\"65\" /></span></p>\n";
print "<br />\n";
print "<p dir=\"ltr\" style=\"line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Please note that all </span>\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "wearebeatgrid.com</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> \n";
print "extensions are monitored and </span>\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "derogatory</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">, \n";
print "i</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">nappropriate</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">, \n";
print "and </span>\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "offensive</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> \n";
print "content is </span>\n";
print "<span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "prohibited</span><span style=\"font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">.</span><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:9pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "(A </span>\n";
print "<span style=\"font-size:9pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span><span style=\"font-size:9pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> \n";
print "symbolizes that only an </span>\n";
print "<span style=\"font-size:9pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "admin </span>\n";
print "<span style=\"font-size:9pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "may access a page) (A </span>\n";
print "<span style=\"font-size:9pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span><span style=\"font-size:9pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> \n";
print "symbolizes that a page is powered by Zoho) </span></p>\n";
print "<br />\n";
print "<br />\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://www.wearebeatgrid.com/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Official Website </span></a></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"http://mail.wearebeatgrid.com\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Mail Service</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://docs.google.com/document/d/1BTHkL71DxDl0XIdaSxB47ZI0zK_jLJQSka0-pgtjJsA/edit?usp=sharing\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "HTML Data</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:8pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "(EXTDOC)</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://social.zoho.com/social/wearebeatgrid/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Social Media</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://campaigns.zoho.com/campaigns/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Promotional Campaigns</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://mailadmin.zoho.com/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Mail Admin</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://people.zoho.com/hr#home/dashboard/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Corporate</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://cm.zoho.com/contacts/wearebeatgrid/index.do#dashboard\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Corporate Contact Manager</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://expense.zoho.com/app#/home/\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Financial</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://projects.zoho.com/portal/wearebeatgrid\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Tasks</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://vault.zoho.com/online/main\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Password Manager</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"https://assist.zoho.com/assist#/home\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Remote Support</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#6aa84f;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Knowledge Base</span><span style=\"font-size:8pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> \n";
print "(TBC)</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"http://csm.wearebeatgrid.com\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "CSM System</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<a href=\"http://login.sethigh.org\" style=\"text-decoration:none;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Office Wifi Login</span></a><span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "</span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "*</span></p>\n";
print "<p dir=\"ltr\" style=\"line-height:2.4;margin-top:0pt;margin-bottom:0pt;\">\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "Corporate Terms </span>\n";
print "<span style=\"font-size:11pt;font-family:Arial;color:#ff0000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "* </span>\n";
print "<span style=\"font-size:8pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">\n";
print "(TBC)</span></p>\n";
print "<br />\n";
print "<hr /></b>\n";
print "<footer><center>This system is Hosted and Managed by the CTO of BeatGrid Music Artist Services.</center></footer>\n";
print "\n";
print "</body>\n";
print "\n";
print "</html>\n";

?>